name: Scale nonpro K8s Cluster

on:
  workflow_dispatch:
    inputs:
      scale_option:
        description: "Select scaling option"
        required: true
        type: choice
        options:
          - up
          - down

jobs:
  scale:
    runs-on: ubuntu-latest

    steps:
      - name: Display selected option
        run: echo "Scaling cluster ${{ github.event.inputs.scale_option }}"
